"""
strategies.py - OTA install strategies for writing directly to the inactive partition.

Two strategies are provided:

  StreamToPartitionStrategy
    Parses the .swu CPIO archive on-the-fly while streaming from HTTP.

    Pipeline (no temporary files anywhere):
      1. Read sw-description from CPIO stream → parse image filename + sha256
      2. Read sw-description.sig              → verify RSA-4096 signature
                                               BEFORE any data is written to disk
      3. Stream the image CPIO entry directly → write to block device,
         accumulate SHA-256 in one pass, verify at end

    If the SHA-256 fails after writing, the partition is dirty but still inactive
    (bootloader still points to active partition) — safe to retry from byte 0.

  MerkleStrategy
    Fetches a manifest.json first (built by build-merkle-manifest.py).
    The manifest contains a RSA-signed Merkle root hash and the SHA-256 of every
    4 KB block in the image.

    Verification order:
      1. RSA signature on root_hash → establishes trust before any data is written
      2. Merkle tree rebuilt from block hashes → root must match the signed root
      3. For each block:
           a. HTTP Range request for that block
           b. SHA-256(block) == manifest leaf hash?
           c. Write block to partition at the correct byte offset
           d. Abort immediately on any mismatch

Package formats:
  StreamToPartition: standard .swu CPIO archive
    [sw-description][sw-description.sig][<raw image file>]
    sw-description must list the image with a sha256 field.

  Merkle: raw image file + companion manifest.json in the same URL directory.
    manifest.json is generated by build-merkle-manifest.py.
"""

import hashlib
import json
import logging
import re
import requests
from typing import Callable, Optional

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.exceptions import InvalidSignature

from config import AgentConfig

logger = logging.getLogger(__name__)

MERKLE_BLOCK_SIZE = 4096  # 4 KB — must match build-merkle-manifest.py

_CPIO_NEWC_MAGIC = b"070701"
_CPIO_CRC_MAGIC  = b"070702"
_CPIO_TRAILER    = "TRAILER!!!"


class StrategyError(Exception):
    pass


# ------------------------------------------------------------------
# Streaming CPIO buffer
# ------------------------------------------------------------------

class _CpioStreamBuffer:
    """
    Wraps a requests streaming response and provides byte-exact reads
    needed to parse a CPIO newc archive without loading it into memory.
    """

    CHUNK = 65536  # 64 KB HTTP read size

    def __init__(self, resp) -> None:
        self._iter = resp.iter_content(chunk_size=self.CHUNK)
        self._buf  = bytearray()
        self._done = False

    def _refill(self, need: int) -> None:
        while len(self._buf) < need and not self._done:
            try:
                chunk = next(self._iter)
                if chunk:
                    self._buf.extend(chunk)
            except StopIteration:
                self._done = True

    def read(self, n: int) -> bytes:
        self._refill(n)
        if len(self._buf) < n:
            raise StrategyError(
                f"Unexpected end of CPIO stream (needed {n}, got {len(self._buf)})"
            )
        data = bytes(self._buf[:n])
        del self._buf[:n]
        return data

    def skip(self, n: int) -> None:
        while n > 0:
            take = min(n, self.CHUNK)
            self._refill(take)
            actual = min(take, len(self._buf))
            if actual == 0:
                raise StrategyError("Unexpected end of CPIO stream during skip")
            del self._buf[:actual]
            n -= actual

    def stream_to_dev(
        self,
        n: int,
        dev,
        hasher,
        image_total: int,
        progress_cb: Optional[Callable[[int, int], None]] = None,
    ) -> int:
        """
        Stream exactly n bytes to the open block device file handle,
        feeding each chunk into hasher (sha256) simultaneously.
        Prints 1%-resolution progress and calls progress_cb(written, image_total).
        Returns the number of bytes written.
        """
        written = 0
        while written < n:
            want = min(self.CHUNK, n - written)
            self._refill(want)
            actual = min(want, len(self._buf))
            if actual == 0:
                raise StrategyError("Unexpected end of CPIO stream during image write")
            chunk = bytes(self._buf[:actual])
            del self._buf[:actual]
            dev.write(chunk)
            hasher.update(chunk)
            written += actual
            pct      = int(written / image_total * 100)
            prev_pct = int((written - actual) / image_total * 100)
            if pct > prev_pct:
                print(
                    f"  Writing image: {pct}%  ({written:,} / {image_total:,} bytes)",
                    flush=True,
                )
            if progress_cb:
                progress_cb(written, image_total)
        return written


# ------------------------------------------------------------------
# Strategy 1: CPIO-aware stream directly to partition, SHA-256 from sw-description
# ------------------------------------------------------------------

class StreamToPartitionStrategy:
    """
    Download a .swu package and write the embedded raw image directly to
    the inactive block device — no temporary files.

    Security model:
      - sw-description is RSA-signed; the signature is verified before
        the first byte of image data is written to the partition.
      - The image SHA-256 in sw-description is the authoritative checksum;
        it is verified after the full write completes.
    """

    def __init__(self, public_key, config: AgentConfig) -> None:
        self._public_key = public_key
        self._config     = config

    def execute(
        self,
        url: str,
        expected_sha256: str,       # whole-.swu hash from MQTT (used as fallback)
        target_partition: str,
        progress_cb: Optional[Callable[[int, int], None]] = None,
    ) -> None:
        """
        Stream the .swu package from url, parse CPIO on-the-fly, verify the
        RSA signature on sw-description, then write the image entry to
        target_partition.  Raises StrategyError on any failure.
        """
        logger.info("StreamToPartition: target device  = %s", target_partition)
        logger.info("StreamToPartition: source URL     = %s", url)

        try:
            resp = requests.get(url, stream=True, timeout=30)
        except requests.RequestException as e:
            raise StrategyError(f"HTTP request failed: {e}") from e

        if resp.status_code != 200:
            raise StrategyError(f"HTTP {resp.status_code} for {url}")

        buf = _CpioStreamBuffer(resp)

        sw_desc_bytes: Optional[bytes] = None
        sw_sig_bytes:  Optional[bytes] = None
        # chunk_map: filename → {sha256, offset, chunk_index}
        chunk_map:         dict = {}
        hashers:           dict = {}   # filename → sha256 hasher
        chunks_remaining:  set  = set()
        total_written = 0

        try:
            with open(target_partition, "wb") as dev:
                while True:
                    # --- CPIO newc header: 110 bytes, all ASCII hex fields ---
                    hdr = buf.read(110)
                    magic = hdr[:6]
                    if magic not in (_CPIO_NEWC_MAGIC, _CPIO_CRC_MAGIC):
                        raise StrategyError(f"Invalid CPIO magic: {magic!r}")

                    namesize = int(hdr[94:102], 16)
                    filesize = int(hdr[54:62], 16)

                    name = buf.read(namesize).rstrip(b"\x00").decode("ascii", errors="replace")
                    _skip_cpio_pad(buf, 110 + namesize)

                    if name == _CPIO_TRAILER:
                        break

                    logger.debug("CPIO entry: name=%r size=%d", name, filesize)

                    # ---- sw-description ----
                    if name == "sw-description":
                        sw_desc_bytes = buf.read(filesize)
                        _skip_cpio_pad(buf, filesize)
                        entries = _parse_image_entries(
                            sw_desc_bytes.decode("utf-8", errors="replace")
                        )
                        if not entries:
                            raise StrategyError(
                                "No image entries found in sw-description. "
                                "Was the package built with build-image-package.sh?"
                            )
                        chunk_map        = {e["filename"]: e for e in entries}
                        chunks_remaining = set(chunk_map.keys())
                        hashers          = {e["filename"]: hashlib.sha256() for e in entries}
                        logger.info(
                            "StreamToPartition: %d image chunk(s) in sw-description",
                            len(entries),
                        )
                        for e in entries:
                            logger.info(
                                "  chunk=%d  filename=%r  offset=%d  sha256=%s…",
                                e["chunk_index"], e["filename"], e["offset"], e["sha256"][:16],
                            )

                    # ---- sw-description.sig ----
                    elif name == "sw-description.sig":
                        if sw_desc_bytes is None:
                            raise StrategyError(
                                "sw-description.sig appeared before sw-description in CPIO archive"
                            )
                        sw_sig_bytes = buf.read(filesize)
                        _skip_cpio_pad(buf, filesize)
                        logger.info("StreamToPartition: verifying RSA-4096 signature on sw-description")
                        self._verify_sig(sw_desc_bytes, sw_sig_bytes)
                        logger.info("StreamToPartition: RSA signature VALID — safe to write image")

                    # ---- image chunk ----
                    elif name in chunk_map:
                        if sw_sig_bytes is None:
                            raise StrategyError(
                                f"Image chunk '{name}' reached before sw-description.sig was verified. "
                                "Package structure is invalid or has been tampered."
                            )
                        info = chunk_map[name]
                        logger.info(
                            "StreamToPartition: writing '%s' (%d bytes) at offset %d → %s",
                            name, filesize, info["offset"], target_partition,
                        )
                        dev.seek(info["offset"])
                        chunk_written = buf.stream_to_dev(
                            filesize, dev, hashers[name], filesize, progress_cb
                        )
                        _skip_cpio_pad(buf, filesize)
                        total_written += chunk_written

                        actual = hashers[name].hexdigest()
                        if actual != info["sha256"]:
                            raise StrategyError(
                                f"SHA-256 mismatch for chunk '{name}'.\n"
                                f"  expected : {info['sha256']}\n"
                                f"  got      : {actual}\n"
                                f"Partition {target_partition} is partially written but "
                                "still inactive — safe to retry."
                            )
                        logger.info("StreamToPartition: '%s' SHA-256 OK", name)
                        chunks_remaining.discard(name)
                        if not chunks_remaining:
                            break  # all chunks written

                    # ---- unknown / extra entries ----
                    else:
                        logger.warning(
                            "StreamToPartition: skipping unexpected CPIO entry '%s' (%d bytes)",
                            name, filesize,
                        )
                        buf.skip(filesize)
                        _skip_cpio_pad(buf, filesize)

        except OSError as e:
            raise StrategyError(f"Write to {target_partition} failed: {e}") from e

        if chunks_remaining:
            raise StrategyError(
                f"CPIO archive ended before all image chunks were written. "
                f"Missing: {chunks_remaining}"
            )

        logger.info(
            "StreamToPartition: wrote %d bytes total to %s", total_written, target_partition
        )

    def _verify_sig(self, sw_desc_bytes: bytes, sig_bytes: bytes) -> None:
        try:
            self._public_key.verify(
                sig_bytes,
                sw_desc_bytes,
                padding.PKCS1v15(),
                hashes.SHA256(),
            )
        except (InvalidSignature, ValueError) as e:
            raise StrategyError(
                "RSA signature on sw-description is INVALID. "
                "Package may be tampered or signed with a different key."
            ) from e


# ------------------------------------------------------------------
# Strategy 2: Merkle hash tree — block-level verification (Android-style)
# ------------------------------------------------------------------

class MerkleStrategy:
    """
    Fetch + verify manifest.json, then download the image one 4 KB block at a
    time via HTTP Range requests.  Each block is verified before it is written.

    Why this is stronger than StreamToPartitionStrategy:
      - Trust is established *before* any data lands on disk (RSA sig check on
        the manifest's root_hash).
      - A corrupted or injected block is caught immediately — only the blocks
        already written need to be re-downloaded on retry, not the whole image.
      - The Merkle tree structure means tampering with any single block hash in
        the manifest would change the root hash, which would invalidate the RSA
        signature — so the manifest itself cannot be forged.
    """

    def __init__(self, public_key, config: AgentConfig) -> None:
        """
        public_key: cryptography RSAPublicKey object (already loaded by PackageVerifier).
        Reusing the same key object avoids loading the PEM file twice.
        """
        self._public_key = public_key
        self._config = config

    def execute(
        self,
        url: str,
        expected_sha256: str,   # whole-file hash from MQTT notification; kept for
        target_partition: str,  # API compatibility but not used — Merkle tree covers integrity
        progress_cb: Optional[Callable[[int, int], None]] = None,
    ) -> None:
        """
        Fetch manifest, verify Merkle tree, download + verify + write each block.
        Raises StrategyError on any failure.
        """
        # Step 1: Fetch and parse manifest
        manifest_url = _manifest_url(url)
        logger.info("MerkleStrategy: fetching manifest from %s", manifest_url)
        manifest = self._fetch_manifest(manifest_url)

        block_size = manifest.get("block_size", MERKLE_BLOCK_SIZE)
        blocks     = manifest["blocks"]          # list of {index, sha256}
        root_hash  = manifest["root_hash"]
        sig_hex    = manifest["root_hash_sig"]

        logger.info(
            "MerkleStrategy: manifest loaded — %d blocks × %d bytes, root=%s…",
            len(blocks), block_size, root_hash[:16],
        )

        # Step 2: Verify RSA signature on root_hash
        logger.info("MerkleStrategy: verifying RSA-4096 signature on root hash")
        self._verify_root_sig(root_hash, sig_hex)
        logger.info("MerkleStrategy: root hash signature VALID")

        # Step 3: Rebuild Merkle tree from block hashes, verify root matches signed value
        leaf_hashes = [b["sha256"] for b in blocks]
        logger.info("MerkleStrategy: rebuilding Merkle tree from %d leaf hashes", len(leaf_hashes))
        computed_root = _build_merkle_root(leaf_hashes)
        if computed_root != root_hash:
            raise StrategyError(
                "Merkle tree root mismatch — the block hash list in the manifest "
                "is inconsistent with the signed root_hash.\n"
                f"  signed root    : {root_hash}\n"
                f"  recomputed root: {computed_root}\n"
                "Manifest may have been tampered after signing."
            )
        logger.info("MerkleStrategy: Merkle tree verified OK")

        # Step 4: Download each block, verify leaf hash, write to partition
        total_blocks = len(blocks)
        logger.info(
            "MerkleStrategy: writing %d blocks to %s …",
            total_blocks, target_partition,
        )

        try:
            with open(target_partition, "r+b") as dev:
                for i, block_info in enumerate(blocks):
                    idx          = block_info["index"]
                    expected_leaf = block_info["sha256"]
                    offset       = idx * block_size

                    data = self._fetch_block(url, offset, block_size)

                    actual_leaf = hashlib.sha256(data).hexdigest()
                    if actual_leaf != expected_leaf:
                        raise StrategyError(
                            f"Block {idx} (offset {offset:#x}) hash mismatch — "
                            "aborting before writing corrupt data.\n"
                            f"  expected : {expected_leaf}\n"
                            f"  got      : {actual_leaf}\n"
                            f"Partition is partially written but still inactive."
                        )

                    dev.seek(offset)
                    dev.write(data)

                    if progress_cb:
                        progress_cb(i + 1, total_blocks)

                    if (i + 1) % 512 == 0 or (i + 1) == total_blocks:
                        logger.info(
                            "MerkleStrategy: %d/%d blocks (%.1f%%)",
                            i + 1, total_blocks, (i + 1) / total_blocks * 100,
                        )
        except OSError as e:
            raise StrategyError(f"Write to {target_partition} failed: {e}") from e

        logger.info("MerkleStrategy: all %d blocks verified and written OK", total_blocks)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _fetch_manifest(self, url: str) -> dict:
        try:
            resp = requests.get(url, timeout=30)
        except requests.RequestException as e:
            raise StrategyError(f"Failed to fetch manifest: {e}") from e
        if resp.status_code != 200:
            raise StrategyError(f"HTTP {resp.status_code} fetching manifest from {url}")
        try:
            return resp.json()
        except ValueError as e:
            raise StrategyError(f"Invalid JSON in manifest: {e}") from e

    def _fetch_block(self, url: str, offset: int, size: int) -> bytes:
        headers = {"Range": f"bytes={offset}-{offset + size - 1}"}
        try:
            resp = requests.get(url, headers=headers, timeout=30)
        except requests.RequestException as e:
            raise StrategyError(
                f"HTTP Range request failed (offset={offset:#x}): {e}"
            ) from e
        if resp.status_code not in (200, 206):
            raise StrategyError(
                f"HTTP {resp.status_code} for block at offset {offset:#x}"
            )
        return resp.content

    def _verify_root_sig(self, root_hash: str, sig_hex: str) -> None:
        try:
            sig_bytes = bytes.fromhex(sig_hex)
            self._public_key.verify(
                sig_bytes,
                root_hash.encode(),
                padding.PKCS1v15(),
                hashes.SHA256(),
            )
        except (InvalidSignature, ValueError) as e:
            raise StrategyError(
                "RSA signature on Merkle root hash is INVALID. "
                "Manifest may be tampered or signed with the wrong key."
            ) from e


# ------------------------------------------------------------------
# Shared helpers
# ------------------------------------------------------------------

def _skip_cpio_pad(buf: _CpioStreamBuffer, size: int) -> None:
    """Skip CPIO padding bytes to align size to a 4-byte boundary."""
    pad = (4 - (size % 4)) % 4
    if pad:
        buf.skip(pad)


def _parse_image_entries(sw_desc_text: str) -> list:
    """
    Parse all image entries from sw-description libconfig text.
    Each entry must have a filename and sha256; offset and chunk_index default to 0.
    Returns a list of dicts sorted by chunk_index.
    """
    images_match = re.search(r'images\s*:\s*\((.*?)\)\s*;', sw_desc_text, re.DOTALL)
    if not images_match:
        return []

    entries = []
    for block in re.finditer(r'\{([^}]+)\}', images_match.group(1), re.DOTALL):
        b        = block.group(1)
        fname_m  = re.search(r'filename\s*=\s*"([^"]+)"', b)
        sha_m    = re.search(r'sha256\s*=\s*"([a-f0-9]{64})"', b)
        off_m    = re.search(r'offset\s*=\s*(\d+)', b)
        cidx_m   = re.search(r'chunk_index\s*=\s*(\d+)', b)
        if not fname_m or not sha_m:
            continue
        entries.append({
            "filename":    fname_m.group(1),
            "sha256":      sha_m.group(1),
            "offset":      int(off_m.group(1))  if off_m  else 0,
            "chunk_index": int(cidx_m.group(1)) if cidx_m else 0,
        })

    entries.sort(key=lambda e: e["chunk_index"])
    return entries


def _manifest_url(package_url: str) -> str:
    """Derive manifest.json URL from the package URL (same directory)."""
    base = package_url.rsplit("/", 1)[0]
    return f"{base}/manifest.json"


def _build_merkle_root(leaf_hashes: list) -> str:
    """
    Build a Merkle tree bottom-up from a list of hex-encoded SHA-256 leaf hashes.
    Returns the root hash as a hex string.

    Padding rule: when a level has an odd number of nodes, the last node is
    duplicated.  This rule must match build-merkle-manifest.py exactly.
    """
    if not leaf_hashes:
        raise StrategyError("Cannot build Merkle tree from an empty leaf list")

    level = list(leaf_hashes)
    while len(level) > 1:
        if len(level) % 2 == 1:
            level.append(level[-1])          # duplicate last node
        next_level = []
        for i in range(0, len(level), 2):
            combined = (level[i] + level[i + 1]).encode()
            next_level.append(hashlib.sha256(combined).hexdigest())
        level = next_level

    return level[0]
